
SELECT B.MONTH_SUBMITTED,
	SUM(B.CNT_MONTH) AS APPLICATIONS_PER_MONTH
FROM
(SELECT 
	app_sbmtd_dt AS DATE_SUBMITTED, 
	MONTH(app_sbmtd_dt ) AS MONTH_SUBMITTED,
	YEAR(app_sbmtd_dt) AS YEAR_SUBMITTED
	1 AS CNT_MONTH
FROM DATABASE_NAME.APPLICATION_FACT AS A
WHERE YEAR_SUBMITTED = 2020 AND DLR_ID.ISIN(SELECT DLR_ID FROM DEALER_DIM WHERE prefrd_dlr_ind = TRUE)
) AS B
GROUP BY MONTH_SUBMITTED
ORDER BY CNT_MONTH DESC
LIMIT 5

SELECT B.DLR_NM
FROM(
SELECT B.DLR_NM,
	CASE
		WHEN A.app_rjctd_dt IS NULL THEN 0
		ELSE 1
	END AS REJECTED_IND,
	1 AS TOTAL_APPLICATIONS
FROM DATABASE_NAME.APPLICATION_FACT AS A
WHERE QUARTER(app_sbmtd_dt) = 4 AND YEAR(app_sbmtd_dt) = 2020
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID)
GROUP BY B.DLR_NM
HAVING SUM(REJECTED_IND) / TOTAL_APPLICATIONS > 0.50;

SELECT E.REGN_NM
FROM(
SELECT A.DLR_ID,
	B.REGN_ID,
	C.REGN_NM,
	CASE
		WHEN D.NEW_USE_DESC = 'New' THEN 0
		ELSE 1
	END AS USE_IND,
	CASE
		WHEN D.NEW_USE_DESC = 'New' THEN 1
		ELSE 0
	END AS NEW_IND,
	CASE
		WHEN app_aprvd_dt IS NOT NULL THEN 1
		ELSE 0 
	END AS APPROVED_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A
WHERE YEAR(app_sbmtd_dt) = 2020 AND QUARTER(app_sbmtd_dt) = 4
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID
LEFT JOIN DATABASE_NAME.VEHICLE_DIM AS D ON A.VEH_ID = D.VEH_ID) AS E
WHERE E.APPROVED_IND = 1
GROUP BY E.REGN_NM
HAVING SUM(USE_IND) > SUM(NEW_IND);

SELECT E.REGN_NM AS REGION_NAME,
	E.DEALER_NM AS DEALER_NAME
FROM 
(SELECT D.DLR_NM,
	D.REGN_NM,
	RANK OVER(PARTITION BY REGN_NM ORDER BY SUM(D.SUBMITTED_APP_IND) DESC) AS RANK_HIGHEST_APPROVED_APPLICATIONS
FROM(
SELECT B.DLR_NM,
	C.REGN_NM,
	CASE 
		WHEN A.app_sbmtd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS SUBMITTED_APP_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID) AS D
GROUP BY D.DLR_NM, D.REGN_NM) AS E 
WHERE E.RANK_HIGHEST_APPROVED_APPLICATIONS = 1;

SELECT
	E.REGN_NM
FROM(
SELECT D.REGN_NM,
	RANK OVER(PARTITION BY D.REGN_NM ORDER BY SUM(D.APP_SUB_IND), SUM(D.APPROVED_APP_IND) DESC) AS RANK_SUBMISSIONS
FROM(
SELECT C.REGN_NM,
	CASE
		WHEN A.app_sbmtd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS APP_SUB_IND,
	CASE
		WHEN A.APP_APRVD_DT IS NOT NULL THEN 1
		ELSE 0
	END AS APPROVED_APP_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A 
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID) AS D
GROUP BY REGN_NM) AS E;

SELECT
	D.MONTH_IND
FROM(
SELECT 
	C.YEAR_IND,
	C.MONTH_IND,
	VAR(C.TOTAL_SUBMITTED) AS VAR_TOTAL_SUBMITTED,
	RANK OVER (PARTITION BY C.MONTH_IND ORDER BY VAR(C.TOTAL_SUBMITTED) DESC) AS YEAR_MONTH_RANK
FROM(
SELECT B.YEAR_IND,
	B.MONTH_IND,
	B.WK_IND,
	SUM(B.SUBMISSIONS_IND) AS TOTAL_SUBMITTED
FROM(
SELECT YEAR(A.app_sbmtd_dt) AS YEAR_IND,
	MONTH(A.app_sbmtd_dt) AS MONTH_IND,
	WEEK(A.app_sbmtd_dt) AS WK_IND,
	CASE
		WHEN A.app_sbmtd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS SUBMISSIONS_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A) AS B
GROUP BY YEAR_IND, MONTH_IND, WK_IND) AS C) AS D
WHERE D.YEAR_MONTH_RANK = 1 AND D.YEAR_IND = 2020
ORDER BY D.VAR_TOTAL_SUBMITTED DESC
LIMIT 1;


SELECT E.REGN_NM AS REGION_NAME,
	E.DLR_NM AS DEALER_NAME
FROM(
SELECT
	D.DLR_NM,
	D.REGN_NM,
	RANK OVER (PARTITION BY D.REGN_NM, D.DLR_NM ORDER BY SUM(REJECTED_APP_IND) ASC) AS RANK_LOWEST_REJECTION_PER_DEALER_IN_REGION
FROM(
SELECT B.DLR_NM,
	C.REGN_NM,
	CASE 
		WHEN A.app_rjctd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS REJECTED_APP_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID) AS D
GROUP BY D.DLR_NM, D.REGN_NM) AS E
WHERE RANK_LOWEST_REJECTION_PER_DEALER_IN_REGION = 1;

SELECT YEAR_ANALYZE,
	SUM(PREF_DEALER_IND) / SUM(TOTAL_SUBMITTED) * 100 AS PERCENTAGE_APPROVED_APPLICATIONS_FROM_PREF_DEALERS
FROM(
SELECT 2020 AS YEAR_ANALYZE,
	CASE 
		WHEN C.prefrd_dlr_ind = TRUE THEN 1
		ELSE 0
	END AS PREF_DEALER_IND,
	1 AS TOTAL_SUBMITTED
(SELECT A.DLR_ID,
	A.APP_APRVD_DT
FROM DATABASE_NAME.APPLICATION_FACT AS A
WHERE YEAR(APP_APRVD_DT) = 2020) AS B
LEFT JOIN DATABASE_NAME.DEALER_DIM AS C ON C.DLR_ID = B.DLR_ID)
GROUP BY YEAR_ANALYZE;

SELECT E.REGN_NM AS REGION_NAME,
	E.DEALER_NM AS DEALER_NAME
FROM 
(SELECT D.DLR_NM,
	D.REGN_NM,
	RANK OVER(PARTITION BY REGN_NM ORDER BY SUM(D.REJECTED_APP_IND) ASC) AS RANK_LOWEST_REJECTED_APPLICATIONS
FROM(
SELECT B.DLR_NM,
	C.REGN_NM,
	CASE 
		WHEN A.app_rjctd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS REJECTED_APP_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID) AS D
GROUP BY D.DLR_NM, D.REGN_NM) AS E 
WHERE E.RANK_LOWEST_REJECTED_APPLICATIONS = 1;

SELECT D.REGN_NM AS REGION_NAME,
	D.LOAN_AMT AS LOAN_AMOUNT
FROM
(SELECT 
	C.REGN_NM,
	A.LOAN_AMT
	CASE 
		WHEN A.app_aprvd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS APPROVED_APP_IND,
	CASE
		WHEN A.loan_amt >= 2000000 THEN 1
		ELSE 0
	END AS BIGGER_LOAN_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID) AS D
WHERE D.BIGGER_LOAN_IND = 1 AND APPROVED_APP_IND = 1;

SELECT E.REGN_NM AS REGION_NAME,
	E.DLR_NM AS DEALER_NAME
FROM(
SELECT
	D.DLR_NM,
	D.REGN_NM,
	RANK OVER (PARTITION BY D.REGN_NM, D.DLR_NM ORDER BY SUM(REJECTED_APP_IND) DESC) AS RANK_HIGHEST_REJECTION_PER_DEALER_IN_REGION
FROM(
SELECT B.DLR_NM,
	C.REGN_NM,
	CASE 
		WHEN A.app_rjctd_dt IS NOT NULL THEN 1
		ELSE 0
	END AS REJECTED_APP_IND
FROM DATABASE_NAME.APPLICATION_FACT AS A
LEFT JOIN DATABASE_NAME.DEALER_DIM AS B ON A.DLR_ID = B.DLR_ID
LEFT JOIN DATABASE_NAME.REGION_DIM AS C ON B.REGN_ID = C.REGN_ID) AS D
GROUP BY D.DLR_NM, D.REGN_NM) AS E
WHERE RANK_HIGHEST_REJECTION_PER_DEALER_IN_REGION = 1;

SELECT A.MONTH_SUBMITTED,
	SUM(A.CNT_MONTH) AS APPLICATIONS_PER_MONTH
FROM
(SELECT 
	app_sbmtd_dt AS DATE_SUBMITTED, 
	MONTH(app_sbmtd_dt ) AS MONTH_SUBMITTED,
	YEAR(app_sbmtd_dt) AS YEAR_SUBMITTED
	1 AS CNT_MONTH
FROM DATABASE_NAME.APPLICATION_FACT
WHERE YEAR_SUBMITTED = 2020) AS A
GROUP BY MONTH_SUBMITTED
ORDER BY CNT_MONTH DESC
LIMIT 5;